/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3sample.Interface;

import assignment3sample.Business.Flight;
import assignment3sample.Business.Flightschedule;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author user
 */
public class ViewFlightPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewCarPanel
     */
    private JPanel rightPanel;
    private Flight flight;
    private List<String> brandList;
    private Flightschedule flightInfor;
    public ViewFlightPanel(JPanel rightPanel, Flightschedule flightInfor,Flight flight, List<String> brandList) {
        this.rightPanel = rightPanel;
        this.flightInfor = flightInfor;
        this.flight = flight;
        this.brandList = brandList;
        initComponents();
        cbBrand.setSelectedItem(flight.getAirliners());
        cbDep.setSelectedItem(flight.getDeparute());
        cbArr.setSelectedItem(flight.getArrive());
        txtSeats.setText(String.valueOf(flight.getSeats()));
        txtFrom.setText(flight.getFrom());
        txtTo.setText(flight.getTo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAvailible = new javax.swing.ButtonGroup();
        bgMaintenance = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblHead = new javax.swing.JLabel();
        cbBrand = new javax.swing.JComboBox<>();
        lblAccNo = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtSeats = new javax.swing.JTextField();
        cbDep = new javax.swing.JComboBox<>();
        cbArr = new javax.swing.JComboBox<>();
        lblYear = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        lblModel1 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHead.setText("Flight detail");

        cbBrand.setModel(new DefaultComboBoxModel(brandList.toArray(new String[0])));
        cbBrand.setEnabled(false);
        cbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBrandActionPerformed(evt);
            }
        });

        lblAccNo.setText("Brand");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtSeats.setEnabled(false);

        cbDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Day", "Afternoon", "Night" }));
        cbDep.setEnabled(false);

        cbArr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Day", "Afternoon", "Night" }));
        cbArr.setEnabled(false);

        lblYear.setText("Seats");

        lblMin.setText("Departure time");

        lblMax.setText("Arrive time");

        lblModel.setText("From");

        txtFrom.setEnabled(false);

        lblModel1.setText("To");

        txtTo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 342, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblModel)
                                            .addComponent(lblModel1))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFrom)
                                            .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblYear)
                                            .addComponent(lblMin)
                                            .addComponent(lblMax))
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSeats)
                                            .addComponent(cbDep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbArr, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAccNo)
                                        .addGap(121, 121, 121)
                                        .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(270, 270, 270))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblHead)
                                .addGap(360, 360, 360))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(8, 8, 8)
                .addComponent(lblHead)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin)
                    .addComponent(cbDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMax)
                    .addComponent(cbArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel1)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        Component[] comps = rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof SchedulePanel) {
                ((SchedulePanel) comp).populate(flightInfor.getFlightList());
                ((SchedulePanel) comp).cleanSearch();
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String air = cbBrand.getSelectedItem().toString();
        String dep = cbDep.getSelectedItem().toString();
        String arr = cbArr.getSelectedItem().toString();
        String from = txtFrom.getText();
        String to = txtTo.getText();
        int seats;
        try {
            seats = Integer.parseInt(txtSeats.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for seats");
            return;
        }
        if (seats < 0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid seats");
            return;
        }
        if (from.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid from");
            return;
        }
        if (to.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid to");
            return;
        }
        flight.updateFlight(air, seats, dep, arr, from, to);

        btnUpdate.setEnabled(true);
        cbBrand.setEnabled(false);
        cbDep.setEnabled(false);
        cbArr.setEnabled(false);
        txtSeats.setEnabled(false);
        txtFrom.setEnabled(false);
        txtTo.setEnabled(false);
        btnSave.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Car Update Successfully");
        flightInfor.updateDateTime();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBrandActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdate.setEnabled(false);
        cbBrand.setEnabled(true);
        cbDep.setEnabled(true);
        cbArr.setEnabled(true);
        txtSeats.setEnabled(true);
        txtFrom.setEnabled(true);
        txtTo.setEnabled(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAvailible;
    private javax.swing.ButtonGroup bgMaintenance;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbArr;
    private javax.swing.JComboBox<String> cbBrand;
    private javax.swing.JComboBox<String> cbDep;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModel1;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
