/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3sample.Interface;

import assignment3sample.Business.Flight;
import assignment3sample.Business.Flightschedule;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author user
 */
public class YourCarPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewCarPanel
     */
    private JPanel rightPanel;
    private Flight car;
    private List<String> brandList;
    private Flightschedule carInfor;
    public YourCarPanel(JPanel rightPanel, Flightschedule carInfor,Flight car, List<String> brandList) {
        this.rightPanel = rightPanel;
        this.carInfor = carInfor;
        this.car = car;
        this.brandList = brandList;
        initComponents();
        /*cbBrand.setSelectedItem(car.getBrand());
        txtYear.setText(String.valueOf(car.getManufactured_year()));
        txtMin.setText(String.valueOf(car.getMin_seats()));
        txtMax.setText(String.valueOf(car.getMax_seats()));
        txtModel.setText(String.valueOf(car.getModel_num()));
        txtCity.setText(String.valueOf(car.getAvailble_city()));*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAvailible = new javax.swing.ButtonGroup();
        bgMaintenance = new javax.swing.ButtonGroup();
        lblYear = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        lblMin = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        rbAva1 = new javax.swing.JRadioButton();
        lblModel1 = new javax.swing.JLabel();
        rbAva2 = new javax.swing.JRadioButton();
        txtCity = new javax.swing.JTextField();
        rbMa1 = new javax.swing.JRadioButton();
        rbMa2 = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        txtYear = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblHead = new javax.swing.JLabel();
        lblAvailible = new javax.swing.JLabel();
        lblAvailible1 = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        cbBrand = new javax.swing.JComboBox<>();
        lblAccNo = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        lblYear.setText("Manufactured year");

        txtSerial.setEnabled(false);

        lblMin.setText("Min seat");

        lblModel.setText("Model");

        txtModel.setEnabled(false);

        rbAva1.setActionCommand("Yes");
        bgAvailible.add(rbAva1);
        rbAva1.setText("Yes");
        rbAva1.setEnabled(false);
        rbAva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAva1ActionPerformed(evt);
            }
        });

        lblModel1.setText("Available City");

        rbAva2.setActionCommand("No");
        bgAvailible.add(rbAva2);
        rbAva2.setText("No");
        rbAva2.setEnabled(false);

        txtCity.setEnabled(false);

        rbMa1.setActionCommand("Yes");
        bgMaintenance.add(rbMa1);
        rbMa1.setText("Yes");
        rbMa1.setEnabled(false);
        rbMa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMa1ActionPerformed(evt);
            }
        });

        rbMa2.setActionCommand("No");
        bgMaintenance.add(rbMa2);
        rbMa2.setText("No");
        rbMa2.setEnabled(false);

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtYear.setEnabled(false);

        txtMin.setEnabled(false);

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHead.setText("Your Car");

        lblAvailible.setText("Available");

        lblAvailible1.setText("Maintenance certificate");

        lblMax.setText("Max seat");

        txtMax.setEnabled(false);

        cbBrand.setModel(new DefaultComboBoxModel(brandList.toArray(new String[0])));
        cbBrand.setEnabled(false);
        cbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBrandActionPerformed(evt);
            }
        });

        lblAccNo.setText("Brand");

        lblSerial.setText("Serial");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(275, 275, 275)
                .addComponent(lblHead)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvailible)
                            .addComponent(lblAccNo)
                            .addComponent(lblYear)
                            .addComponent(lblMin)
                            .addComponent(lblMax)
                            .addComponent(lblSerial)
                            .addComponent(lblModel)
                            .addComponent(lblModel1)
                            .addComponent(lblAvailible1))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMa1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbMa2))
                            .addComponent(txtCity)
                            .addComponent(txtModel)
                            .addComponent(txtSerial)
                            .addComponent(txtMax)
                            .addComponent(txtYear)
                            .addComponent(txtMin)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbAva1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbAva2))
                            .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(lblHead))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailible)
                    .addComponent(rbAva1)
                    .addComponent(rbAva2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMax)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerial)
                    .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel1)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailible1)
                    .addComponent(rbMa1)
                    .addComponent(rbMa2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbAva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAva1ActionPerformed

    private void rbMa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMa1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        Component[] comps = rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof SchedulePanel) {
                ((SchedulePanel) comp).populate(carInfor.getFlightList());
                ((SchedulePanel) comp).cleanSearch();
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String ava = bgAvailible.getSelection().getActionCommand();
        String brand = cbBrand.getSelectedItem().toString();
        String maintain = bgMaintenance.getSelection().getActionCommand();
        int year, min, max, serial;
        try {
            year = Integer.parseInt(txtYear.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for year");
            return;
        }
        if (year < 0 || year > 2019) {
            JOptionPane.showMessageDialog(null, "Please enter a valid year");
            return;
        }
        try {
            min = Integer.parseInt(txtMin.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for min seat");
            return;
        }
        if (min < 0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid min seat");
            return;
        }
        try {
            max = Integer.parseInt(txtMax.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for max seat");
            return;
        }
        if (max < 0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid max seat");
            return;
        }
        if(max < min) {
            JOptionPane.showMessageDialog(null, "Max seat must bigger than min seat");
            return;
        }
        try {
            serial = Integer.parseInt(txtSerial.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for serial");
            return;
        }
        if (serial < 0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid serial");
            return;
        }
        if (txtModel.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid model");
            return;
        }
        if (txtCity.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid city");
            return;
        }
        car.updateFlight(brand, year, String.valueOf(min), String.valueOf(max), txtModel.getText(), txtCity.getText());

        btnUpdate.setEnabled(true);
        rbAva1.setEnabled(false);
        rbAva2.setEnabled(false);
        cbBrand.setEnabled(false);
        txtYear.setEnabled(false);
        txtMin.setEnabled(false);
        txtMax.setEnabled(false);
        txtSerial.setEnabled(false);
        txtModel.setEnabled(false);
        txtCity.setEnabled(false);
        rbMa1.setEnabled(false);
        rbMa2.setEnabled(false);
        btnSave.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Car Update Successfully");
        carInfor.updateDateTime();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBrandActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdate.setEnabled(false);
        rbAva1.setEnabled(true);
        rbAva2.setEnabled(true);
        cbBrand.setEnabled(true);
        txtYear.setEnabled(true);
        txtMin.setEnabled(true);
        txtMax.setEnabled(true);
        txtSerial.setEnabled(true);
        txtModel.setEnabled(true);
        txtCity.setEnabled(true);
        rbMa1.setEnabled(true);
        rbMa2.setEnabled(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAvailible;
    private javax.swing.ButtonGroup bgMaintenance;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbBrand;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblAvailible;
    private javax.swing.JLabel lblAvailible1;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModel1;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblYear;
    private javax.swing.JRadioButton rbAva1;
    private javax.swing.JRadioButton rbAva2;
    private javax.swing.JRadioButton rbMa1;
    private javax.swing.JRadioButton rbMa2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
